import type { Metadata } from "next"
import "@stream-io/video-react-sdk/dist/css/styles.css"
import "./globals.css"
import { ClerkProvider } from "@clerk/nextjs"
import { Toaster } from "@/components/ui/toaster"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body className="antialiased">
          {children}
          <Toaster />
        </body>
      </ClerkProvider>
    </html>
  )
}
